---
# tasks file for fetch-facts-role
# - name: Print some debug information 
#   vars: 
#     msg: |
#         Ansible Distribution: {{ ansible_distribution }}
#         Ansible Dist version: {{ ansible_distribution_version }}
#         Other facts: {{ ansible_facts }}
#   debug: 
#     msg: "{{ msg.split('\n') }}"       
#   tags: debug_info

- name: save facts to file
  copy:
    content: "{{ ansible_facts }}" 
    dest: "/tmp/cmdb-facts-{{ inventory_hostname}}.txt"

- name: Specifying a path directly
  ansible.builtin.fetch:
    src: "/tmp/cmdb-facts-{{ inventory_hostname}}.txt"
    dest: /tmp/prefix-{{ inventory_hostname }}.txt
    flat: yes